### ISSUE TITLE
node module 을 ignore해서 올려주세요

### ISSUE THREAD

**Issue by siwony** [qoxogus/NodeJs-Express#1]
github에다가 모듈을 ignore 해서 올리는것을 추천합니다
모듈을 올리지 않아도 package.json에 의존 모듈들이 명시 되어있어서 나중에 `npm install` 하시면 package.json 에 명시되어 있는 모듈들이 install 됩니다.
나중에 pull 받을때 무거운 module까지 받으면 오래걸리잖아요

**Comment by qoxogus** [comment]
넹
